using Datasheets2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Datasheets2.Search
{
    public class ItemFoundEventArgs : EventArgs
    {
        public ISearchResult Item { get; private set; }

        public ItemFoundEventArgs(ISearchResult item)
        {
            this.Item = item;
        }
    }

    public interface ISearchResult
    {
        string PartName { get; }
        string Description { get; }
        string Manufacturer { get; }
        Uri DatasheetUrl { get; }
    }

    public interface ISearchProvider
    {
        /// <summary>
        /// Begin a search using the search provider
        /// </summary>
        /// <param name="query">The query term to search</param>
        /// <param name="ct">Token to cancel the search with</param>
        Task SearchAsync(string query, CancellationToken ct);

        /// <summary>
        /// Download the PDF from a search result generated by this search provider
        /// </summary>
        /// <remarks>
        /// Do not use this with search results from a different search provider.
        /// </remarks>
        /// <param name="item">The item to download</param>
        /// <param name="destPath">Where to download the file to</param>
        /// <param name="ct">Token to cancel the download with</param>
        Task DownloadPdfAsync(ISearchResult item, string destPath, CancellationToken ct);

        /// <summary>
        /// Event called when a new item is retrieved from the search
        /// </summary>
        event EventHandler<ItemFoundEventArgs> ItemFound;
    }
}
